### ISSUE TITLE
Update to newer lodash

### ISSUE THREAD

**Issue by djmitche** [pifantastic/node-sentry-api#6]
@pifantastic the versions of lodash that this library uses are considered vulnerable to prototype pollution.  Would you accept a PR to use a newer lodash?

**Comment by pifantastic** [comment]
@djmitche I haven't touched this in ages. I think it's probably safer for me to take down this repo. 🙈  Feel free to fork! I would imagine there are probably much better Sentry API clients out there for node.

**Comment by djmitche** [comment]
Will do!  I'm not sure why we chose this one, to be honest :)

**Comment by djmitche** [comment]
Would you consider handing over the npm module?  I'm going to fork this to the Taskcluster org, and you can see that we use the library and publish a number of other node libraries like fast-azure-storage.

**Comment by pifantastic** [comment]
@djmitche I would be happy to hand it over :)

**Comment by djmitche** [comment]
Sounds good!  If you want to add me (I'm djmitche there too) as an admin then I'll add the remainder of the Taskcluster team.

**Comment by djmitche** [comment]
---> https://github.com/taskcluster/node-sentry-api/issues/1
